[
  {
    "id": 143,
    "post_type": "content",
    "is_anonymous": 1,
    "anonymous_name": "An293094nymous",
    "anonymous_bg_color": "pink",
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "3 days ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "for,good,test,own",
    "data": {
      "id": 17,
      "post_id": 143,
      "user_id": 8,
      "type": "general",
      "title": "Roommate MIA(LITERALLY NO WHERE TO BE SEEN) for almost 3 years, pays rent 95% of the time, cant get a hold of them, what are my options?",
      "text_body": "CONTEXT. Moved in with someone about 5 years ago(No, I didnt know them, yes I know, they came across very genuine and upfront, and we hung out multiple times before we concluded this would be a good fit), and about 3 years ago, they said they were leaving for a few weeks to go help their mom, and hasnt been back since. They, FOR THE MOST PART, pay rent, but every once in a while, it doesnt go through. I have been in contact with my landlord about the situation but I'm basically SOL; my roommate needs to remove themselves from the lease, I cant reach them, nor have any evidence they still walk this earth. Furthermore, since they still pay rent here or there, they obviously have every right to be here and keep their belongings here.\r\n\r\nI feel this context is important for some reason, the things they left here are QUESTIONABLE. For example, THEIR CAT. THEY ABANDONNED THEIR WHOLE ASS CAT. He is now my cat, thanks for asking. They also left memorial placards for their late father and cat, they spent a whole 1000$ on this post memorial package for their cat and they just left it here?! And if any of you are like \"you can't just take someones cat\", Ill have you know, when their other cat died, they looked at my precious angel and said \"I wish it were you instead of him!\". So no, they dont deserve my cat.\r\n\r\nI have tried reaching out to them across multiple platforms (msg, Insta, PSN, Gmail, their best friends also havent heard from them, I also reached out to their mom through her MLS Realtor site) and I get NOTHING. The landlord of my building has also reached out to them with no avail. They have even had their mail redirected (I can tell because they dont get any mail aside from a debt collection agency, I googled the logo). I have a vague idea of where they said they would be, but I dont necessarily have the time to drive out to the GTA and ask wtf, let alone where to start.\r\n\r\nIm trying to navigate the LSO to contact a lawyer, but I fear they wont be able to get anywhere with this situation because of the second unwilling party. I am doing this because I am not readily willing to move. This is my home, my neighbourhood, I havent lived anywhere else longer besides my family home growing up, also, HAVE YOU SEEN RENT PRICES, FUQNOOO. I dont want to be reimbursed for the few times I had to pay rent, I just want them off the lease so I can have the flexibility of talking to my roommate face to face when they dont pay rent.\r\n\r\nLiterally any advice would be cool, or speculate as to what their doing below, its fun and cathartic. I personally think they fled the country from an embezzlement scheme gone wrong, because who does this?!\r\n\r\nEDIT: I figured out how to add a photo of my cat!\r\n\r\nEdit 2 : Its actually closer to 86% of the time over the three years, but this year alone, theyre at 50%.\r\n\r\n++[RASCALCATS](https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Fsend-me-stupid-kitty-pics-im-sad-v0-c1pruegtkx8d1.jpeg%3Fwidth%3D4624%26format%3Dpjpg%26auto%3Dwebp%26s%3Dc20adb4dbaf4d25dfc08415374ea95c465166805)++",
      "media_url": "[\"https://nahidea.picocolor.site/img/content/1777366039374-Screenshot-2026-03-17-142905.webp\"]",
      "media_type": "[\"image\"]"
    }
  },
  {
    "id": 142,
    "post_type": "confession",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "6 days ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "adv",
    "data": {
      "id": 19,
      "post_id": 142,
      "user_id": 8,
      "type": "heartbreak",
      "title": "davcda",
      "media_url": "https://nahidea.picocolor.site/img/confession/1777088690366-Screenshot-2025-12-10-214503.webp",
      "media_type": "image",
      "is_anonymous": 0
    }
  },
  {
    "id": 141,
    "post_type": "confession",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "6 days ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "xz",
    "data": null
  },
  {
    "id": 140,
    "post_type": "confession",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "6 days ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "xxz",
    "data": null
  },
  {
    "id": 139,
    "post_type": "content",
    "is_anonymous": 1,
    "anonymous_name": "An128071nymous",
    "anonymous_bg_color": "pink",
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "6 days ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "ok,tv,idk,Movie,show",
    "data": {
      "id": 16,
      "post_id": 139,
      "user_id": 8,
      "type": "educational",
      "title": "Why so many adaptations suck.",
      "text_body": "Many people are frustrated that a lot of adaptations are awful, do horribly, and yet all Hollywood can seem to do is make more adaptations. \"why not just make original work?\" many decry. \"Why do film makers not just make their own stories?\" .\r\n\r\nBad adaptations are bad for many reasons, but the core methodology is often the same. As a writer, I've seen even my colleagues make these same mistakes in real time.\r\n\r\n**Why are Adaptations made?**\r\n\r\nWith media production costs being higher than ever, there is much to lose from a film performing poorly. There are many challenges a studio must cross, but the hardest hurdle for a film to cross is the first one.\r\n\r\nExhibit A:\r\n\r\nYou and your friend have decided to see a movie. Your friend pulls up the website and see what's playing, seeing several new films playing at the local whatever the hell. The first movie is an original scifi that cost a hundred million.\r\n\r\nyou ask \"whats it about?\"\r\n\r\n**THIS IS THE SCARIEST QUESTION IN THE WORLD.**\r\n\r\nWhether or not your film, that you possibly spent millions of dollars on, gets seen or makes its money back hinges on it. Across the world, this question gets asked again and again and it relys on your friend with horrible pitching skills. Its an uphill climb that's made worse by streaming services and youtube giving you millions of choices.\r\n\r\nYou could hope you get good word of mouth, but thats more chance than anything. You could spend more on marketing, but that just increases the amount you'll lose if it flops.\r\n\r\nExhibit B:\r\n\r\nYou and your friend have decided to see a movie. Your friend pulls up the website and see what's playing.\r\n\r\n\"Batman\" He says.\r\n\r\nAn just like that, this question, which haunts the dreams of studio execs, is gone. through cultural osmosis and an established audience, you will immediately know what the movie will be about. not the details, but enough. You might even be a fan of this character, and be excited to see the newest depiction.\r\n\r\nWhile the movie still might do badly, at least you'll get a certain amount of people in the theatre opening weekend in the first place. if its good, word of mouth might even make more people see it. Less risk. less chance of loosing money.\r\n\r\nStudios know this. so they greenlight an adaptation rather than risk it on the new project.\r\n\r\n**The same dogshit lifehack**\r\n\r\nI'll tell you a secret. Do you know who hates adaptations most of all?\r\n\r\nDIRECTORS.\r\n\r\nevery director/writer (and I do mean every director) is in filmmaking because of their gigantic egos. they don't want to make a starwars movie, the want to make their OWN scifi space opera. the one they dreamed of when they were in highschool. the one they wont stop pitching to anyone who will listen.\r\n\r\nbut, sadly, films cost insane amounts of money. Sure, you could try and make it on your own, but indie film making is even riskier than normal filmmaking.\r\n\r\nAt this point, the director thinks of this \"genius\" life hack. a life hack, he thinks only he has thought of.\r\n\r\n\"I'll make my OWN scifi space opera, but call it an adaptation!\"\r\n\r\nAnd so, they rename their main characters to \"rob skywalker\" and \"Dumbass the hutt\". They add in light references to the source material. just enough to make the studios satisfied.\r\n\r\nThen, the audience, who has finally been waiting for their favorite story to come to screen start getting excited. The director is happy he can tell his own story. the Studio sees dollar signs.\r\n\r\nThe director starts to do press for the film.\r\n\r\n++[IT](https://www.cinemablend.com/new/Why-Fantastic-Four-Cast-Was-Told-Read-Comics-70324.html?utm_source=zergnet.com&utm_medium=referral&utm_campaign=zergnet_443981)++\r\n\r\n++[NEVER](https://www.ign.com/articles/eli-roth-previews-his-approach-to-borderlands-movie)++\r\n\r\n++[WORKS.](https://kotaku.com/god-of-war-tv-ronald-d-moore-battlestar-galactica-1851770751)++\r\n\r\n(this mindset is so pervasive I have even more examples)\r\n\r\n++[Example 4](https://www.inverse.com/article/15172-dragonball-evolution-writer-pens-an-apology-to-fans-7-years-later)++\r\n\r\n++[Example 5](https://boundingintocomics.com/tv-shows/halo-showrunner-steven-kane-says-writing-team-didnt-look-at-or-talk-about-the-game-we-talked-about-the-characters-and-the-world)++",
      "media_url": "[\"https://nahidea.picocolor.site/img/content/1777087902287-Screenshot-2025-12-10-214503.webp\",\"https://nahidea.picocolor.site/img/content/1777087902289-Screenshot-2025-12-10-214624.webp\",\"https://nahidea.picocolor.site/img/content/1777087902290-Screenshot-2025-12-11-105403.webp\",\"https://nahidea.picocolor.site/img/content/1777087902290-Screenshot-2025-12-11-105424.webp\",\"https://nahidea.picocolor.site/img/content/1777087902290-Screenshot-2025-12-11-105435.webp\"]",
      "media_type": "[\"image\",\"image\",\"image\",\"image\",\"image\"]"
    }
  },
  {
    "id": 138,
    "post_type": "content",
    "is_anonymous": 1,
    "anonymous_name": "An049737nymous",
    "anonymous_bg_color": "pink",
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "6 days ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "d,gdn,dgn,gdndg,dnd",
    "data": null
  },
  {
    "id": 137,
    "post_type": "question",
    "is_anonymous": 1,
    "anonymous_name": "An081693nymous",
    "anonymous_bg_color": "skyblue",
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "1 week ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "sacsa,ascsa,acsa",
    "data": {
      "id": 60,
      "post_id": 137,
      "question_type": "openend",
      "question_related_to": "heartbreak",
      "is_anonymous": 0,
      "status": "open",
      "title": "saca",
      "media_url": "https://nahidea.picocolor.site/img/question/1777019798059-Screenshot 2025-12-02 140744.webp"
    }
  },
  {
    "id": 136,
    "post_type": "question",
    "is_anonymous": 1,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "1 week ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "question,test",
    "data": {
      "id": 59,
      "post_id": 136,
      "question_type": "openend",
      "question_related_to": "in_love",
      "is_anonymous": 0,
      "status": "open",
      "title": "test openend",
      "media_url": "https://nahidea.picocolor.site/img/question/1777013296281-Screenshot 2025-12-28 231141.webp"
    }
  },
  {
    "id": 135,
    "post_type": "question",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "1 week ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "vdsd,opened",
    "data": {
      "id": 58,
      "post_id": 135,
      "question_type": "openend",
      "question_related_to": "in_love",
      "is_anonymous": 0,
      "status": "open",
      "title": "openend",
      "media_url": "https://nahidea.picocolor.site/img/question/1776954811499-Screenshot 2025-12-11 105456.webp"
    }
  },
  {
    "id": 134,
    "post_type": "confession",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "1 week ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "confession,tes",
    "data": {
      "id": 18,
      "post_id": 134,
      "user_id": 8,
      "type": "in_love",
      "title": "test the confession",
      "media_url": "https://nahidea.picocolor.site/img/confession/1776954613863-Screenshot 2025-12-30 232513.webp",
      "media_type": "image",
      "is_anonymous": 0
    }
  },
  {
    "id": 133,
    "post_type": "content",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "1 week ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "tv,show,tvshow,hero,Movie",
    "data": {
      "id": 15,
      "post_id": 133,
      "user_id": 8,
      "type": "experience",
      "title": "\"Should superheroes kill\" is a fundamentally uninteresting theme because it is a solved problem (Mostly Invincible, some others)",
      "text_body": "Mostly inspired by Invincible S2 (or was it 3?) and the dumb conclusion of Mark, having struggled all season with whether he should kill, melodramatically concluding with his serious face that the next time he finds a threat to family, he's going to kill them.\r\n\r\nOmg, so dramatic. Such a topic that anyone really cares about.\r\n\r\nMost if not all societies already have a moral standard for when a member is allowed to kill someone in self-defense. That standard is usually whether you're in danger of death or serious bodily harm. Often they include defense of other in this scenario. Not all places place sexual crimes like rape or technically not lethal like locking you up in a torture dungeon in this category, but \"they're trying to kill you or someone else\" is usually a decent marker for when lethal force is justified.\r\n\r\nIt is doubly annoying when the work is set in America, which among other things has had like over a century of establishing a somewhat consistent moral standard for the use of force. If you'd be justified to shoot someone with your gun, you'd be justified to laser eye them or snikt them or punch them into the sun. The fact that the other guy often also has superpowers makes it more justifiable, not less, because the threat and thereby danger to others is higher in this case. You don't even need to do the whole \"I won't kill you but I don't have to save you from this position that would definitely kill you\" and then spend screentime navel gazing about the minute difference. Just do it. You're fine.\r\n\r\nAnd yes, sure not everyone has the mental fortitude to kill someone even if they'd be justified. But if I wanted to consume media about people who aren't willing to use justified violence, why am I watching superhero media to start with?\r\n\r\nNow, that's not to say that a hypothetical piece of media that explores the actual ramifications of a pacifist superhero can't be interesting, but that's just it, it has to explore the ramifications. And that's simply what we don't get in most \"should supes kill\" media, which typically try to set up some kind of personal moral dilemma that is neither necessary nor interesting to watch.\r\n\r\nTldr: should supes kill is fundamentally uninteresting because there's already a legal and moral framework under which it fits, and watching main characters wangst about it is like watching someone work through if 1+1=2.",
      "media_url": "[\"https://nahidea.picocolor.site/img/content/1776954514357-Screenshot 2025-12-02 140744.webp\",\"https://nahidea.picocolor.site/img/content/1776954514360-Screenshot 2025-12-02 220858.webp\",\"https://nahidea.picocolor.site/img/content/1776954514360-Screenshot 2025-12-04 133013.webp\",\"https://nahidea.picocolor.site/img/content/1776954514360-Screenshot 2025-12-04 133052.webp\",\"https://nahidea.picocolor.site/img/content/1776954514361-Screenshot 2025-12-06 183734.webp\"]",
      "media_type": "[\"image\",\"image\",\"image\",\"image\",\"image\"]"
    }
  },
  {
    "id": 132,
    "post_type": "content",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "1 week ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "sa,sac,sacsa,av",
    "data": {
      "id": 14,
      "post_id": 132,
      "user_id": 8,
      "type": "educational",
      "title": " z xz xz",
      "text_body": "cszs",
      "media_url": "[\"https://nahidea.picocolor.site/img/content/1776743635205-Screenshot 2025-12-02 140744.webp\",\"https://nahidea.picocolor.site/img/content/1776743635207-Screenshot 2025-12-02 220858.webp\"]",
      "media_type": "[\"image\",\"image\"]"
    }
  },
  {
    "id": 131,
    "post_type": "content",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "2 weeks ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "qfe,efvew,wqef,wfeb,qewfe",
    "data": {
      "id": 13,
      "post_id": 131,
      "user_id": 8,
      "type": "general",
      "title": "qwfce v",
      "text_body": "**jcsdvc**\n\n*dsvsnedv*\n\n++dvsiowevwe++\n\n~~rfwrejc~~ \n\newfiafc\n\nergforeijvc v\n\n# rewfgireghv\n\n## wrgirrfpcihfe\n\n### grefich'rwg\n\n- rgfirwhehvcr\n- gre\n- vewr\n\n1. wefwef\n2. efwef\n3. ewfwef\n\n```\ne\n```\n\n```\nwfwe\n```\n\n[ef](ace)\n\n> ew\n\n",
      "media_url": "[\"https://nahidea.picocolor.site/img/content/1776411113675-Screenshot 2025-12-02 140744.webp\",\"https://nahidea.picocolor.site/img/content/1776411113676-Screenshot 2025-12-02 220858.webp\",\"https://nahidea.picocolor.site/img/content/1776411113677-Screenshot 2025-12-04 133013.webp\",\"https://nahidea.picocolor.site/img/content/1776411113677-Screenshot 2025-12-04 133052.webp\",\"https://nahidea.picocolor.site/img/content/1776411113677-Screenshot 2025-12-06 183734.webp\"]",
      "media_type": "[\"image\",\"image\",\"image\",\"image\",\"image\"]"
    }
  },
  {
    "id": 130,
    "post_type": "content",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "2 weeks ago",
    "status": "open",
    "username": "meanleapha",
    "tags": null,
    "data": {
      "id": 12,
      "post_id": 130,
      "user_id": 8,
      "type": "experience",
      "title": "test third",
      "text_body": "**jcsdvc**\r\n\r\n*dsvsnedv*\r\n\r\n++dvsiowevwe++\r\n\r\n~~rfwrejc~~ \r\n\r\newfiafc\r\n\r\nergforeijvc v\r\n\r\n# rewfgireghv\r\n\r\n## wrgirrfpcihfe\r\n\r\n### grefich'rwg\r\n\r\n- rgfirwhehvcr\r\n- gre\r\n- vewr\r\n\r\n1. wefwef\r\n2. efwef\r\n3. ewfwef\r\n\r\n```\r\ne\r\n```\r\n\r\n```\r\nwfwe\r\n```\r\n\r\nef\r\n\r\new",
      "media_url": "[]",
      "media_type": "[]"
    }
  },
  {
    "id": 129,
    "post_type": "content",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "2 weeks ago",
    "status": "open",
    "username": "meanleapha",
    "tags": null,
    "data": null
  },
  {
    "id": 128,
    "post_type": "content",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "2 weeks ago",
    "status": "open",
    "username": "meanleapha",
    "tags": null,
    "data": null
  },
  {
    "id": 127,
    "post_type": "question",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "3 weeks ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "Movie,ranking,Tv-show,Apocalypse,zombie",
    "data": {
      "id": 57,
      "post_id": 127,
      "question_type": "rankingorder",
      "question_related_to": "party_story",
      "is_anonymous": 0,
      "status": "open",
      "title": "final test on the ranking",
      "media_url": "https://nahidea.picocolor.site/img/question/1775703388097-Screenshot 2026-01-04 185954.webp",
      "items": [
        {
          "id": 13,
          "ranking_id": 13,
          "position": 1,
          "item_text": "The Walking Dead",
          "question_id": 57
        },
        {
          "id": 14,
          "ranking_id": 13,
          "position": 2,
          "item_text": "World War Z",
          "question_id": 57
        },
        {
          "id": 15,
          "ranking_id": 13,
          "position": 3,
          "item_text": "Train to Busan",
          "question_id": 57
        },
        {
          "id": 16,
          "ranking_id": 13,
          "position": 4,
          "item_text": "I am Legend",
          "question_id": 57
        },
        {
          "id": 17,
          "ranking_id": 13,
          "position": 6,
          "item_text": "Resident Evil",
          "question_id": 57
        },
        {
          "id": 18,
          "ranking_id": 13,
          "position": 5,
          "item_text": "Alive",
          "question_id": 57
        },
        {
          "id": 19,
          "ranking_id": 13,
          "position": 8,
          "item_text": "Silent Hill",
          "question_id": 57
        },
        {
          "id": 20,
          "ranking_id": 13,
          "position": 7,
          "item_text": "Maze Runner",
          "question_id": 57
        },
        {
          "id": 21,
          "ranking_id": 13,
          "position": 10,
          "item_text": "Apocalypse Z",
          "question_id": 57
        },
        {
          "id": 22,
          "ranking_id": 13,
          "position": 9,
          "item_text": "The last of Us(season 1)",
          "question_id": 57
        }
      ]
    }
  },
  {
    "id": 126,
    "post_type": "question",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "3 weeks ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "starBoy",
    "data": {
      "id": 3,
      "post_id": 126,
      "question_type": "rating",
      "question_related_to": "gossip",
      "is_anonymous": 0,
      "status": "open",
      "title": "test the rating",
      "media_url": null,
      "question_id": 56,
      "rating_icon_id": 1
    }
  },
  {
    "id": 125,
    "post_type": "question",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "3 weeks ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "range,test",
    "data": {
      "id": 4,
      "post_id": 125,
      "question_type": "range",
      "question_related_to": "anxiety",
      "is_anonymous": 0,
      "status": "open",
      "title": "leap the the range",
      "media_url": null,
      "question_id": 55,
      "range_min": "0.00",
      "range_max": "20.00",
      "step": "1.00",
      "default_range_value": "9.00"
    }
  },
  {
    "id": 124,
    "post_type": "question",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "3 weeks ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "bomboclat",
    "data": {
      "id": 54,
      "post_id": 124,
      "question_type": "multiplechoice",
      "question_related_to": "overthinking",
      "is_anonymous": 0,
      "status": "open",
      "title": "leapOverthinking",
      "media_url": "https://nahidea.picocolor.site/img/question/1775701452755-Screenshot 2025-12-01 104103.webp",
      "choices": [
        {
          "id": 9,
          "multiplechoice_id": 4,
          "choice_text": "leap sucessor",
          "question_id": 54
        },
        {
          "id": 10,
          "multiplechoice_id": 4,
          "choice_text": "leapTHefounder",
          "question_id": 54
        },
        {
          "id": 11,
          "multiplechoice_id": 4,
          "choice_text": "leapSecond to none",
          "question_id": 54
        },
        {
          "id": 12,
          "multiplechoice_id": 4,
          "choice_text": "leapDaGreat",
          "question_id": 54
        }
      ]
    }
  },
  {
    "id": 123,
    "post_type": "question",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "3 weeks ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "leapDaGreat",
    "data": {
      "id": 53,
      "post_id": 123,
      "question_type": "singlechoice",
      "question_related_to": "overthinking",
      "is_anonymous": 0,
      "status": "open",
      "title": "test the single choice",
      "media_url": null,
      "choices": [
        {
          "id": 10,
          "singlechoice_id": 13,
          "choice_text": "leap",
          "question_id": 53
        },
        {
          "id": 11,
          "singlechoice_id": 13,
          "choice_text": "whose leap",
          "question_id": 53
        },
        {
          "id": 12,
          "singlechoice_id": 13,
          "choice_text": "leap da great",
          "question_id": 53
        },
        {
          "id": 13,
          "singlechoice_id": 13,
          "choice_text": "still leap",
          "question_id": 53
        }
      ]
    }
  },
  {
    "id": 122,
    "post_type": "question",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "3 weeks ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "bomboclaet",
    "data": {
      "id": 3,
      "post_id": 122,
      "question_type": "closedend",
      "question_related_to": "heartbreak",
      "is_anonymous": 0,
      "status": "open",
      "title": "test the closedend",
      "media_url": null,
      "question_id": 52,
      "yes_title": "yes plase",
      "no_title": "no please",
      "yes_media_url": null,
      "no_media_url": null
    }
  },
  {
    "id": 121,
    "post_type": "question",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "3 weeks ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "jesus,please,work",
    "data": {
      "id": 51,
      "post_id": 121,
      "question_type": "openend",
      "question_related_to": "situationship",
      "is_anonymous": 0,
      "status": "open",
      "title": "test the openend",
      "media_url": "https://nahidea.picocolor.site/img/question/1775700922758-Screenshot 2025-03-13 084158.webp"
    }
  },
  {
    "id": 120,
    "post_type": "content",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "3 weeks ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "best,test,the",
    "data": {
      "id": 11,
      "post_id": 120,
      "user_id": 8,
      "type": "experience",
      "title": "now it content",
      "text_body": null,
      "media_url": "[\"https://nahidea.picocolor.site/img/content/1775700856381-Screenshot 2025-12-01 104103.webp\",\"https://nahidea.picocolor.site/img/content/1775700856381-Screenshot 2025-12-02 140744.webp\",\"https://nahidea.picocolor.site/img/content/1775700856381-Screenshot 2025-12-02 220858.webp\",\"https://nahidea.picocolor.site/img/content/1775700856382-Screenshot 2025-12-04 133013.webp\",\"https://nahidea.picocolor.site/img/content/1775700856382-Screenshot 2025-12-01 104103.webp\"]",
      "media_type": "[\"image\",\"image\",\"image\",\"image\",\"image\"]"
    }
  },
  {
    "id": 119,
    "post_type": "confession",
    "is_anonymous": 0,
    "anonymous_name": null,
    "anonymous_bg_color": null,
    "likes_count": 0,
    "comments_count": 0,
    "views_count": 0,
    "created_at": "3 weeks ago",
    "status": "open",
    "username": "meanleapha",
    "tags": "mi,U,hate,y",
    "data": {
      "id": 17,
      "post_id": 119,
      "user_id": 8,
      "type": "in_love",
      "title": "fresh test ",
      "media_url": "https://nahidea.picocolor.site/img/confession/1775700795908-Screenshot 2025-12-30 233124.webp",
      "media_type": "image",
      "is_anonymous": 0
    }
  }
]